//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.24 at 07:49:42 PM MSK 
//


package com.figaf.content.converter.transformer.directory.dto.global;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.figaf.integration.directory.dto.javastack.global package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * SenderAgreementCreate a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.figaf.integration.directory.dto.javastack.global
     * 
     */
    public ObjectFactory() {
    }

    /**
     * SenderAgreementCreate an instance of {@link LONGDescription }
     * 
     */
    public LONGDescription createLONGDescription() {
        return new LONGDescription();
    }

    /**
     * SenderAgreementCreate an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

}
